### PR TITLE
Updated README with a logo

### PR DESCRIPTION
**Pull request by obeid**
Happy Birthday Foglemeister.

### CODE REVIEW

**Comment by fogleman** [comment]
LOL

**Comment by fogleman** [comment]
You didn't like my mustache idea?

**Comment by obeid** [comment]
Oh I just remembered the mustache idea, nothing against it but all I took from the name was the pun on Mr. Clean. I will whip something up really quick.

**Comment by obeid** [comment]
Hooray for second rounds, notice the faces in the negative space. Pick one and we'll take it from there.

**Comment by fogleman** [comment]
Dude these are awesome. I'll have to think about which is my favorite.

**Comment by fogleman** [comment]
I think #3 is my favorite.

**Comment by obeid** [comment]
So, I took #3 and made a number of variations. The first is pretty much untouched. The last option tries to reinforce the negative-space faces by splitting the main mustache.

**Comment by fogleman** [comment]
1 or 4.

OK, what do you think of this concept? :)

eyes

**Comment by fogleman** [comment]
I like the idea of it being more of a character... with some personality.

**Comment by obeid** [comment]
Haha! Hilarious. You really like that whole explicit is better than implicit idea, ha. 
I like it, I can explore what we can do with that.

**Comment by fogleman** [comment]
Added to README.

**Pull request closed without merging**
